{% set version = "6.8.0" %}

package:
  name: pypdf-split
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pypdf/pypdf-{{ version }}.tar.gz
    sha256: cb7eaeaa4133ce76f762184069a854e03f4d9a08568f0e0623f7ea810407833b
  - folder: src
    url: https://github.com/py-pdf/pypdf/archive/refs/tags/{{ version }}.tar.gz
    sha256: fd86950620d59e9b8580355321a394e93488b2951725e1c38d26d2061a20dd2b

build:
  number: 0

outputs:
  - name: pypdf
    build:
      script: cd dist && python -m pip install . -vv --no-deps --no-build-isolation
      skip: True  # [py<39]
    requirements:
      host:
        - python
        - flit-core >=3.11,<4
        - pip
      run:
        - python
        - typing_extensions >=4.0  # [py<311]
    test: &simple-test
      imports:
        - pypdf
      commands:
        - pip check
      requires:
        - pip

  - name: pypdf-with-crypto
    build:
      skip: True  # [py<36]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pypdf", exact=True) }}
        - cryptography
    test: *simple-test

  - name: pypdf-with-image
    build:
      skip: True  # [py<36]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pypdf", exact=True) }}
        - pillow >=8.0.0
    test: *simple-test

  - name: pypdf-with-full
    build:
      skip: True  # [py<36]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
    test: *simple-test

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  description: |
    pypdf is a free and open-source pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. pypdf can retrieve text and metadata from PDFs as well.
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  dev_url: https://github.com/py-pdf/pypdf
  doc_url: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
