{% set version = "3.2.1" %}

package:
  name: pypdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pypdf/pypdf-{{ version }}.tar.gz
  sha256: ac6bcd4492b55c95f58f7e3a6e8e113588244bdfb21c8ee60da6db399725b8dd

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0
  noarch: python

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - dataclasses
    - python >=3.6
    - typing_extensions >=3.10.0.0

test:
  imports:
    - pypdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  dev_url: https://github.com/py-pdf/pypdf
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://pypdf.readthedocs.io

extra:
  recipe-maintainers:
    - MartinThoma
