{% set name = "pypdf" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypdf-{{ version }}.tar.gz
  sha256: ac6bcd4492b55c95f58f7e3a6e8e113588244bdfb21c8ee60da6db399725b8dd

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
    - typing_extensions >=3.10
  run:
    - python
    - typing_extensions >=3.10.0.0  # [py<310]
    - dataclasses  # [py<37]

test:
  imports:
    - pypdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pypdf/
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  dev_url: https://github.com/py-pdf/pypdf
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MartinThoma
