{% set version = "3.16.4" %}

package:
  name: pypdf-split
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pypdf/pypdf-{{ version }}.tar.gz
    sha256: 01927771b562d4ba84939ef95b393f0179166da786c5db710d07f807c52f480d
  - folder: src
    url: https://github.com/py-pdf/pypdf/archive/refs/tags/{{ version }}.tar.gz
    sha256: aa0538e47425dee6fb0dbfa357b5b48c2625021378ec7d681bce8c21205ede54

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6

outputs:

  - name: pypdf
    build:
      script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      noarch: python
    requirements:
      host:
        - flit-core >=3.9,<4
        - pip
        - python >=3.6
      run:
        - dataclasses
        - python >=3.6
        - typing_extensions >=3.7.4.3
    test: &simple-test
      imports:
        - pypdf
      commands:
        - pip check
      requires:
        - pip

  - name: pypdf-with-crypto
    build: &noarch-python
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - {{ pin_subpackage("pypdf", exact=True) }}
        - cryptography
        - python >=3.7
    test: *simple-test

  - name: pypdf-with-image
    build: *noarch-python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("pypdf", exact=True) }}
        - pillow >=8.0.0
        - python >=3.6
    test: *simple-test

  - name: pypdf-with-full
    build: *noarch-python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
        - python >=3.6
    test: *simple-test

  - name: _pypdf-with-full-tests
    build: *noarch-python
    requirements:
      host:
        - python >=3.6
      run:
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-full", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
        - python >=3.6
    test:
      files:
        - test_all.py
      source_files:
        - src/pyproject.toml
        - src/tests
        - src/resources
      imports:
        - pypdf
      commands:
        - pip check
        - python test_all.py
      requires:
        - fpdf
        - mypy
        - pip
        - pytest-cov
        - pytest-socket
        - pytest-timeout
        - types-pillow

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  license: BSD-3-Clause
  license_file: dist/LICENSE
  dev_url: https://github.com/py-pdf/pypdf
  doc_url: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
