{% set version = "4.2.0" %}

package:
  name: pypdf-split
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/p/pypdf/pypdf-{{ version }}.tar.gz
    sha256: fe63f3f7d1dcda1c9374421a94c1bba6c6f8c4a62173a59b64ffd52058f846b1
  - folder: src
    url: https://github.com/py-pdf/pypdf/archive/refs/tags/{{ version }}.tar.gz
    sha256: 4096459bdb19df0231360617f2266d8068a40b9eb202bbea9c54274a320f0c55

build:
  number: 0

outputs:
  - name: pypdf
    build:
      script: cd dist && python -m pip install . -vv --no-deps --no-build-isolation
      skip: True  # [py<36]
    requirements:
      host:
        - python
        - flit-core >=3.9,<4
        - pip
      run:
        - python
        - typing_extensions >=4.0  # [py<311]
    test: &simple-test
      imports:
        - pypdf
      commands:
        - pip check
      requires:
        - pip

  - name: pypdf-with-crypto
    build:
      skip: True  # [py<36]
    requirements:
      host:
        - python
        - flit-core >=3.9,<4
        - pip
      run:
        - python
        - {{ pin_subpackage("pypdf", exact=True) }}
        - cryptography
    test: *simple-test

  - name: pypdf-with-image
    build:
      skip: True  # [py<36]
    requirements:
      host:
        - python
        - flit-core >=3.9,<4
        - pip
      run:
        - python
        - {{ pin_subpackage("pypdf", exact=True) }}
        - pillow >=8.0.0
    test: *simple-test

  - name: pypdf-with-full
    build:
      skip: True  # [py<36]
    requirements:
      host:
        - python
        - flit-core >=3.9,<4
        - pip
      run:
        - python
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
    test: *simple-test

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  description: |
    pypdf is a free and open-source pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. pypdf can retrieve text and metadata from PDFs as well.
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  dev_url: https://github.com/py-pdf/pypdf
  doc_url: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
