{% set name = "pypdf" %}
{% set version = "6.14.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 7873f502fe4385e79539b21d872392dc0c4e3714327c15881cbc7fbfd1f95b25

build:
  number: 0

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv --no-deps --no-build-isolation
      skip: true  # [py<39]
    requirements:
      host:
        - python
        - flit-core >=3.11,<4
        - pip
      run:
        - python
        - typing_extensions >=4.0  # [py<311]
    test: &simple-test
      source_files:
        - tests
        - resources
      files:
        - test_all.py
      imports:
        - pypdf
      commands:
        - pip check
        # we need to ignore test_all.py because it is not a test file
        - set "PYTEST_ADDOPTS=--ignore=test_all.py"  # [win]
        - python test_all.py                          # [win]
        - PYTEST_ADDOPTS="--ignore=test_all.py" python test_all.py  # [not win]
      requires:
        - pip
        - pytest
        - pytest-cov
        - pyyaml
        - pillow
        - fonttools

  - name: {{ name }}-with-crypto
    build:
      skip: true  # [py<39]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pypdf", exact=True) }}
        - cryptography >=3.0
    test: *simple-test

  - name: {{ name }}-with-image
    build:
      skip: true  # [py<39]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pypdf", exact=True) }}
        - pillow >=8.0.0
    test: *simple-test

  - name: {{ name }}-with-full
    build:
      skip: true  # [py<39]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage("pypdf-with-crypto", exact=True) }}
        - {{ pin_subpackage("pypdf-with-image", exact=True) }}
        - {{ pin_subpackage("pypdf", exact=True) }}
    test: *simple-test

about:
  home: https://pypi.org/project/pypdf
  summary: A pure-python PDF library capable of splitting, merging, cropping, and transforming PDF files
  description: |
    pypdf is a free and open-source pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. It can also add custom data, viewing options, and passwords to PDF files. pypdf can retrieve text and metadata from PDFs as well.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/py-pdf/pypdf
  doc_url: https://pypdf.readthedocs.io

extra:
  feedstock-name: pypdf
  recipe-maintainers:
    - MartinThoma
    - bollwyvl
